services:
  postgres:
    build: 
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  products:
    build: 
      context: ./
      dockerfile: ./docker/products/Dockerfile
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
      PORT: ${PORT}
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  postgres:
